package com.info.discover

//list any import classes here.
import com.info.discover.ruleengine.solution.pojo.RuleSourceInput


//declare any global variables here
global com.info.discover.ruleengine.solution.pojo.DataDateMappingVO dataDateMappingVO;

rule "DataDateMappingRule"
	no-loop true
    when
        ruleSourceInput: RuleSourceInput(sourceType: sourceDataFactType)
    then
        dataDateMappingVO
end
